# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake3

# The command to remove a file.
RM = /usr/bin/cmake3 -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/csmajs/jgies011/final-project-dcast162-nkile001-dryan011-jgies011

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/csmajs/jgies011/final-project-dcast162-nkile001-dryan011-jgies011

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake3 -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake3 -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake3 --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake3 -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/jgies011/final-project-dcast162-nkile001-dryan011-jgies011/CMakeFiles /home/csmajs/jgies011/final-project-dcast162-nkile001-dryan011-jgies011/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/jgies011/final-project-dcast162-nkile001-dryan011-jgies011/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock_main.dir/build.make googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock.dir/build.make googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest_main.dir/build.make googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest.dir/build.make googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

src/AlphabeticalSort.o: src/AlphabeticalSort.cpp.o

.PHONY : src/AlphabeticalSort.o

# target to build an object file
src/AlphabeticalSort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/AlphabeticalSort.cpp.o
.PHONY : src/AlphabeticalSort.cpp.o

src/AlphabeticalSort.i: src/AlphabeticalSort.cpp.i

.PHONY : src/AlphabeticalSort.i

# target to preprocess a source file
src/AlphabeticalSort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/AlphabeticalSort.cpp.i
.PHONY : src/AlphabeticalSort.cpp.i

src/AlphabeticalSort.s: src/AlphabeticalSort.cpp.s

.PHONY : src/AlphabeticalSort.s

# target to generate assembly for a file
src/AlphabeticalSort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/AlphabeticalSort.cpp.s
.PHONY : src/AlphabeticalSort.cpp.s

src/Book.o: src/Book.cpp.o

.PHONY : src/Book.o

# target to build an object file
src/Book.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Book.cpp.o
.PHONY : src/Book.cpp.o

src/Book.i: src/Book.cpp.i

.PHONY : src/Book.i

# target to preprocess a source file
src/Book.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Book.cpp.i
.PHONY : src/Book.cpp.i

src/Book.s: src/Book.cpp.s

.PHONY : src/Book.s

# target to generate assembly for a file
src/Book.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Book.cpp.s
.PHONY : src/Book.cpp.s

src/GenreSearch.o: src/GenreSearch.cpp.o

.PHONY : src/GenreSearch.o

# target to build an object file
src/GenreSearch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/GenreSearch.cpp.o
.PHONY : src/GenreSearch.cpp.o

src/GenreSearch.i: src/GenreSearch.cpp.i

.PHONY : src/GenreSearch.i

# target to preprocess a source file
src/GenreSearch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/GenreSearch.cpp.i
.PHONY : src/GenreSearch.cpp.i

src/GenreSearch.s: src/GenreSearch.cpp.s

.PHONY : src/GenreSearch.s

# target to generate assembly for a file
src/GenreSearch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/GenreSearch.cpp.s
.PHONY : src/GenreSearch.cpp.s

src/ISBNSearch.o: src/ISBNSearch.cpp.o

.PHONY : src/ISBNSearch.o

# target to build an object file
src/ISBNSearch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/ISBNSearch.cpp.o
.PHONY : src/ISBNSearch.cpp.o

src/ISBNSearch.i: src/ISBNSearch.cpp.i

.PHONY : src/ISBNSearch.i

# target to preprocess a source file
src/ISBNSearch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/ISBNSearch.cpp.i
.PHONY : src/ISBNSearch.cpp.i

src/ISBNSearch.s: src/ISBNSearch.cpp.s

.PHONY : src/ISBNSearch.s

# target to generate assembly for a file
src/ISBNSearch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/ISBNSearch.cpp.s
.PHONY : src/ISBNSearch.cpp.s

src/KeyWordSearch.o: src/KeyWordSearch.cpp.o

.PHONY : src/KeyWordSearch.o

# target to build an object file
src/KeyWordSearch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/KeyWordSearch.cpp.o
.PHONY : src/KeyWordSearch.cpp.o

src/KeyWordSearch.i: src/KeyWordSearch.cpp.i

.PHONY : src/KeyWordSearch.i

# target to preprocess a source file
src/KeyWordSearch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/KeyWordSearch.cpp.i
.PHONY : src/KeyWordSearch.cpp.i

src/KeyWordSearch.s: src/KeyWordSearch.cpp.s

.PHONY : src/KeyWordSearch.s

# target to generate assembly for a file
src/KeyWordSearch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/KeyWordSearch.cpp.s
.PHONY : src/KeyWordSearch.cpp.s

tests/tests.o: tests/tests.cpp.o

.PHONY : tests/tests.o

# target to build an object file
tests/tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/tests.cpp.o
.PHONY : tests/tests.cpp.o

tests/tests.i: tests/tests.cpp.i

.PHONY : tests/tests.i

# target to preprocess a source file
tests/tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/tests.cpp.i
.PHONY : tests/tests.cpp.i

tests/tests.s: tests/tests.cpp.s

.PHONY : tests/tests.s

# target to generate assembly for a file
tests/tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/tests.cpp.s
.PHONY : tests/tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... test"
	@echo "... src/AlphabeticalSort.o"
	@echo "... src/AlphabeticalSort.i"
	@echo "... src/AlphabeticalSort.s"
	@echo "... src/Book.o"
	@echo "... src/Book.i"
	@echo "... src/Book.s"
	@echo "... src/GenreSearch.o"
	@echo "... src/GenreSearch.i"
	@echo "... src/GenreSearch.s"
	@echo "... src/ISBNSearch.o"
	@echo "... src/ISBNSearch.i"
	@echo "... src/ISBNSearch.s"
	@echo "... src/KeyWordSearch.o"
	@echo "... src/KeyWordSearch.i"
	@echo "... src/KeyWordSearch.s"
	@echo "... tests/tests.o"
	@echo "... tests/tests.i"
	@echo "... tests/tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

